name: MSSP-SOC
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the main and staging branch
  push:
    branches:
      -staging
      -main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dependencies
      - uses: actions/checkout@v1
      - run: |
          echo "Dfvdfvdfvdfvdfv"
         
         
