# This is a basic workflow to help you get started with Actions

name: MSSP-SOC

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - main
    - staging
  pull_request:
    branches: 
      - main
      - staging
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   changedfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          node index.js "${{ steps.files.outputs.all }}"
      - id: abc
        uses: jitterbit/get-changed-files@v1
        with:
          format: json
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: | 
          npm install axios
          node index.js "${{ steps.abc.outputs.all }}"
  
   build:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v1

        - name: Run a one-line script
          run: echo Hello, world!
        - name: Run a multi-line script
          run: |
            python abc.py
