name: MSSP-SOC
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the main and staging branch
  pull_request:
  push:
    branches:
      -staging
      -main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - uses: actions/checkout@v1
         with:
          token: ${{ secrets.GITHUB_TOKEN }}
       - run: |
           apt install python3
           python3 abc.py
         
         
