on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: abubakrx/testing_workflow@v1
      with:
        who-to-greet: 'MSSP-SOC Team'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"



# This is a basic workflow to help you get started with Actions

# name: SOC-Testing WorkFlow

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events for the main and staging branch
#   pull_request:
#   push:
#     branches:
#       -staging
#       -main

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
# #     - uses: actions/checkout@v1
# #     - name: setup python 3.7
# #       uses: actions/setup-python@v1
# #       with: 
# #        python-version: 3.7
      
# #     - name: install dependencies
# #     run: |
# #       python -m pip install --upgrade pip
# #       pip install  
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#        - uses: actions/checkout@v2
#        - id: files
#          uses: jitterbit/get-changed-files@v1
#        - run: |
#           node index.js "${{ steps.files.outputs.all }}"
#        - id: abc
#          uses: jitterbit/get-changed-files@v1
#          with:
#           format: json
#           token: ${{ secrets.GITHUB_TOKEN }}
#        - run: | 
#            npm install axios
#            node index.js "${{ steps.abc.outputs.all }}"
        
